name: Build Kernel X test
on:
  workflow_dispatch:

jobs:
  build:
    name: Runs-arm
    runs-on: ubuntu-24.04-arm
    steps:
    - name: test
      run: |
        sudo apt-get update
        sudo apt-get install git neofetch 
        sudo lscpu
        sudo lsmem
        neofetch
